In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
z = np.array([2.0, -1.0, 0.1])
z

array([ 2. , -1. ,  0.1])

In [3]:
# Define Softmax function
def softmax(z):
    return np.exp(z)/np.sum(np.exp(z))

In [4]:
# Generate probabilities
probs = softmax(z)
probs

array([0.83378101, 0.04151151, 0.12470747])

In [5]:
# Sum of all probabilities
np.sum(probs)

0.9999999999999999

In [6]:
# Create a tensor object
z = torch.tensor([[2.0, -1.0, 0.1], [0.1, 4.0, -2.0]])
z

tensor([[ 2.0000, -1.0000,  0.1000],
        [ 0.1000,  4.0000, -2.0000]])

In [7]:
# Use built-in function to generate probabilities for different instances as shown above
torch.softmax(z, dim=1)

tensor([[0.8338, 0.0415, 0.1247],
        [0.0198, 0.9778, 0.0024]])

### Cross Entropy Loss

In [8]:
# 1 instance/ 1 obs. (target - labels : 0, 1, 2)
y =  torch.tensor([[1,0,0]], dtype=torch.float64) # label = 0
z = torch.tensor([[2.0, -1.0, 0.1]])

loss = nn.CrossEntropyLoss()
loss(z, y)

tensor(0.1818, dtype=torch.float64)

In [9]:
torch.softmax(z, dim=1)

tensor([[0.8338, 0.0415, 0.1247]])

In [10]:
-((1*np.log(0.8338)))

0.18176171353544054

In [11]:
# 3 instances/ 3 obs. (target - labels : 0, 1, 2)
y =  torch.tensor([[1,0,0], [1,0,0], [0,0,2]], dtype=torch.float64) # label = 0, 0, 2
z = torch.tensor([[2.0, -1.0, 0.1],
                  [2.9, -1.0, 0.3],
                  [200.0, -1.0, 10.0]])

loss = nn.CrossEntropyLoss()
loss(z, y)

tensor(126.7574, dtype=torch.float64)

In [12]:
# Generates probabilities for each instance based on raw logit values defined above (z).
torch.softmax(z, dim=1)

tensor([[0.8338, 0.0415, 0.1247],
        [0.9136, 0.0185, 0.0679],
        [1.0000, 0.0000, 0.0000]])

In [13]:
# Generates maximum logit values and their corresponding predicted label.
torch.max(z, dim=1)

torch.return_types.max(
values=tensor([  2.0000,   2.9000, 200.0000]),
indices=tensor([0, 0, 0]))